import { LifeSkill, ActionCard } from '@/types/lifeos';

export interface LifePillarGroup {
  id: string;
  number: number;
  name: string;
  tagline: string;
  icon: string;
  skills: LifeSkill[];
}

export const LIFE_SKILLS_CATALOG: LifeSkill[] = [
  // ==========================================
  // PILLAR 1: HEALTH, EMERGENCY & CLINICAL VAULT
  // ==========================================
  {
    id: 'skill-1-emergency-sos',
    pillarId: 'pillar-1-health',
    pillarName: 'HEALTH, EMERGENCY & CLINICAL VAULT',
    name: 'Family Emergency & SOS Sentinel',
    icon: '🛡️',
    purpose: 'Maintains a 1-tap emergency medical dossier including hospital preferences, blood groups, doctor contacts, and cashless TPA insurance cards.',
    triggers: {
      voiceCues: ['Update emergency contact', 'Add Apollo Hospital as preferred hospital', 'Here is our new health insurance card'],
      multimodal: ['Photo of health insurance plastic card or e-card PDF'],
      scheduledCron: 'Surfaced during onboarding or when no active health policy is detected',
    },
    targetArtifact: 'Google Drive (/LifeOS/Health/Emergency_Dossier.pdf) & Google Keep',
    googleService: 'Google Drive',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '🛡️ EMERGENCY DOSSIER',
      sourceContext: 'Triggered by Family Emergency & SOS Sentinel Protocol',
      headline: 'Emergency Medical Dossier Ready for Rapid Cashless Admission',
      synthesis: 'Sum Insured: ₹25,00,000 (HDFC ERGO Optima Secure). TPA Desk Hotline: 1800-2666-400. Blood Groups: A+ (Self), B+ (Spouse), O+ (Father). Preferred Network Hospital: Apollo Hospital Jubilee Hills.',
      urgency: 'critical',
      isKeystone: true,
      targetEntity: 'Apollo Hospital TPA Desk / Emergency Network',
      targetArtifact: 'Google Drive (/LifeOS/Health/Emergency_Dossier.pdf)',
      googleService: 'Google Drive',
      pillarName: 'HEALTH, EMERGENCY & CLINICAL VAULT',
      skillId: 'skill-1-emergency-sos',
      previewType: 'document',
      previewData: {
        docTitle: 'Family Emergency & Cashless TPA Medical Dossier',
        sections: [
          { title: 'Primary Policy', content: 'HDFC ERGO Optima Secure #2819-8921-992. Sum Insured: ₹25 Lakhs + 100% Secure Bonus.' },
          { title: 'Preferred Network Hospitals', content: '1. Apollo Hospital (1.8 km) - Cashless Empanelled\n2. Manipal Hospital (4.2 km) - Cashless Empanelled' },
          { title: 'Emergency Contacts', content: 'Dr. R. K. Sharma (Family Physician): +91 98490 12345\nTPA 24x7 Cashless Desk: 1800-2666-400 (Member ID: HDF-99214)' },
          { title: 'Critical Patient Notes', content: 'Father: Allergic to Penicillin. Diabetic (Metformin 500mg).' },
        ],
      },
    },
  },
  {
    id: 'skill-2-clinical-vault',
    pillarId: 'pillar-1-health',
    pillarName: 'HEALTH, EMERGENCY & CLINICAL VAULT',
    name: 'Family Clinical & Health Vault',
    icon: '🩺',
    purpose: 'Securely parses, indexes, and trends diagnostic lab reports, prescription histories, and doctor profiles.',
    triggers: {
      voiceCues: ['Doctor prescribed Metformin 500mg once daily after dinner', 'Uploaded blood test report'],
      multimodal: ['Photo or PDF of blood test reports (lipid profile, HbA1c, thyroid panel) or prescription slips'],
    },
    targetArtifact: 'Google Sheets (Health_Biomarkers_Ledger) + Google Drive (/LifeOS/Medical_Records/)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '🩺 CLINICAL VAULT',
      sourceContext: 'Extracted from Apollo Diagnostics Blood Report PDF',
      headline: 'Diagnostic Report Extracted: Comprehensive Lipid Profile & HbA1c',
      synthesis: 'Biomarkers parsed: Total Cholesterol: 195 mg/dL (Normal <200), LDL: 112 mg/dL (Optimal), HbA1c: 5.6% (Non-diabetic range). Filed under Father profile. Next retest scheduled in 6 months.',
      urgency: 'high',
      isKeystone: true,
      targetEntity: 'Father Health Profile (Google Sheets)',
      targetArtifact: 'Google Sheets (Health_Biomarkers_Ledger)',
      googleService: 'Google Sheets',
      pillarName: 'HEALTH, EMERGENCY & CLINICAL VAULT',
      skillId: 'skill-2-clinical-vault',
      previewType: 'document',
      previewData: {
        docTitle: 'Diagnostic Lab Extraction: Apollo Diagnostics',
        sections: [
          { title: 'Extracted Values', content: '• Total Cholesterol: 195 mg/dL (Normal)\n• HDL: 48 mg/dL (Optimal)\n• LDL: 112 mg/dL (Borderline Normal)\n• Triglycerides: 142 mg/dL (Normal <150)\n• HbA1c: 5.6% (Normal)' },
          { title: 'Clinical Recommendation', content: 'Values show 8% improvement in triglycerides compared to Q1 2026 ledger. Continue low-glycemic dietary regimen.' },
        ],
      },
    },
  },
  {
    id: 'skill-3-preventive-screening',
    pillarId: 'pillar-1-health',
    pillarName: 'HEALTH, EMERGENCY & CLINICAL VAULT',
    name: 'Preventive Health Screening Cadence',
    icon: '📅',
    purpose: 'Maintains age-specific annual health checkup schedules, preventive screenings, dental cleanings, and vaccination cadences.',
    triggers: {
      voiceCues: ['When is my dental cleaning due?', 'Book annual preventive health checkup'],
      multimodal: ['Doctor receipt or dental invoice'],
      scheduledCron: 'Annual screening cadence audit (evaluated against last clinical ledger date)',
    },
    targetArtifact: 'Google Calendar (Annual screening window) + Google Tasks (Book appointment)',
    googleService: 'Google Calendar',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '📅 PREVENTIVE CADENCE',
      sourceContext: 'Scheduled Cadence Trigger: 11 months since last dental checkup',
      headline: 'Schedule Annual Dental & Eye Screening Cadence for Saturday 11 AM',
      synthesis: 'Last dental prophylaxis was conducted 11 months ago. Pre-cleared Saturday 11:00 AM slot at Smile Dental Clinic. Chief of Staff will auto-block Google Calendar and log booking in Google Tasks.',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Smile Dental Clinic / Dr. Ananya Sen',
      targetArtifact: 'Google Calendar (Preventive Health Slot)',
      googleService: 'Google Calendar',
      pillarName: 'HEALTH, EMERGENCY & CLINICAL VAULT',
      skillId: 'skill-3-preventive-screening',
      previewType: 'document',
      previewData: {
        docTitle: 'Preventive Cadence Booking Spec',
        sections: [
          { title: 'Due Preventive Screens', content: '1. Bi-annual Dental Scaling & Cavity Inspection (Last: Nov 2025)\n2. Comprehensive Dilated Eye Exam (Last: Oct 2025)' },
          { title: 'Calendar Hold Proposed', content: 'Saturday, 11:00 AM - 12:30 PM (No conflicting business meetings detected).' },
        ],
      },
    },
  },

  // ==========================================
  // PILLAR 2: DAILY VITALITY & BODY (NUTRITION, FITNESS, SLEEP)
  // ==========================================
  {
    id: 'skill-4-nutrition-pantry',
    pillarId: 'pillar-2-vitality',
    pillarName: 'DAILY VITALITY & BODY (NUTRITION, FITNESS, SLEEP)',
    name: 'Family Nutrition & Pantry Optimizer',
    icon: '🥗',
    purpose: 'Weekly household meal planning, healthy regional recipes, grocery restocking, and instant macro estimation from plate photos.',
    triggers: {
      voiceCues: ['Add rolled oats and almonds to grocery list', 'Plan dinner for tonight', 'Logged lunch'],
      multimodal: ['Snapping a photo of a meal plate (dal, 2 rotis, paneer sabzi, curd)'],
    },
    targetArtifact: 'Google Sheets (Nutrition_Log) + Google Tasks (Shared_Grocery_List)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '🥗 NUTRITION OPTIMIZER',
      sourceContext: 'Extracted from camera snap of lunch plate',
      headline: 'Log High-Protein Regional Lunch: 580 kcal | 26g Protein to Nutrition Sheet',
      synthesis: 'Plate components recognized: Yellow Moong Dal (1.5 cups), 2 Multigrain Rotis, Paneer Bhurji (100g), Fresh Curd (100g). Macros: 580 kcal, 26g Protein, 62g Carbs, 18g Healthy Fats.',
      urgency: 'low',
      isKeystone: false,
      targetEntity: 'Nutrition & Pantry Ledger',
      targetArtifact: 'Google Sheets (Nutrition_Log)',
      googleService: 'Google Sheets',
      pillarName: 'DAILY VITALITY & BODY (NUTRITION, FITNESS, SLEEP)',
      skillId: 'skill-4-nutrition-pantry',
      previewType: 'data',
      previewData: {
        docTitle: 'Meal Macro Breakdown',
        sections: [
          { title: 'Plate Items', content: '• Yellow Moong Dal: 180 kcal | 9g Protein\n• 2 Multigrain Rotis: 160 kcal | 5g Protein\n• Paneer Bhurji: 180 kcal | 10g Protein\n• Fresh Curd: 60 kcal | 2g Protein' },
          { title: 'Daily Target Progress', content: 'Total Daily Intake: 1,340 / 2,100 kcal | Protein: 78g / 130g target (60%).' },
        ],
      },
    },
  },
  {
    id: 'skill-5-fitness-workout',
    pillarId: 'pillar-2-vitality',
    pillarName: 'DAILY VITALITY & BODY (NUTRITION, FITNESS, SLEEP)',
    name: 'Physical Fitness & Workout Programmer',
    icon: '🏋️',
    purpose: 'Progressive home workouts, dumbbell strength programs, mobility drills, and habit tracking.',
    triggers: {
      voiceCues: ['Did 4 sets of dumbbell shoulder presses and 20 min cycling', 'Plan today workout', 'Logged gym session'],
      multimodal: ['Smartwatch workout summary screenshot'],
      scheduledCron: 'Daily workout routine launcher chip',
    },
    targetArtifact: 'Google Sheets (Workout_Volume_Tracker) + Google Tasks',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '🏋️ FITNESS PROGRAMMER',
      sourceContext: 'Voice directive logged: 4 sets shoulder presses & 20 min cycling',
      headline: 'Record Upper Body Push Volume & 20m Zone-2 Cardio in Training Ledger',
      synthesis: 'Volume logged: DB Overhead Press (18kg x 4 sets x 10 reps = 720kg volume load), Lateral Raises (10kg x 3 sets). Cardio: 20 min cycling @ 132 bpm avg HR (Zone 2). Cumulative weekly volume on track (104%).',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Workout Volume Ledger',
      targetArtifact: 'Google Sheets (Workout_Volume_Tracker)',
      googleService: 'Google Sheets',
      pillarName: 'DAILY VITALITY & BODY (NUTRITION, FITNESS, SLEEP)',
      skillId: 'skill-5-fitness-workout',
      previewType: 'document',
      previewData: {
        docTitle: 'Training Session Summary',
        sections: [
          { title: 'Push Exercises', content: '1. DB Overhead Press: 4x10 @ 18kg\n2. Incline DB Bench: 3x12 @ 22kg\n3. DB Lateral Raises: 3x15 @ 10kg' },
          { title: 'Conditioning', content: 'Stationary Cycling: 20 mins, 185 kcal burned, Zone 2 aerobic base target maintained.' },
        ],
      },
    },
  },
  {
    id: 'skill-6-sleep-architecture',
    pillarId: 'pillar-2-vitality',
    pillarName: 'DAILY VITALITY & BODY (NUTRITION, FITNESS, SLEEP)',
    name: 'Sleep Architecture Optimizer',
    icon: '🌙',
    purpose: 'Tracks sleep hygiene habits, evening wind-down buffers, circadian alignment, and wakeful energy.',
    triggers: {
      voiceCues: ['Slept 7.5 hours, felt rested', 'Activate bedtime buffer', 'Logged Oura ring score'],
      scheduledCron: 'Evening Cron (9:30 PM): Prompts Evening Shutdown Routine & Digital Sunset',
    },
    targetArtifact: 'Google Sheets (Sleep_Energy_Ledger)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '🌙 SLEEP SHIELD',
      sourceContext: 'Evening Cron Trigger (9:30 PM) for 11:00 PM Bedtime Goal',
      headline: 'Activate Evening Digital Sunset & 20m Wind-Down Routine',
      synthesis: 'To safeguard your 7h 45m sleep window and 6:30 AM wake target, initiate screen dimming, amber light shift, and the 20-minute audio wind-down player. Room temperature set to 20°C.',
      urgency: 'high',
      isKeystone: true,
      targetEntity: 'Evening Wind-Down Protocol',
      targetArtifact: 'Google Sheets (Sleep_Energy_Ledger)',
      googleService: 'Google Sheets',
      pillarName: 'DAILY VITALITY & BODY (NUTRITION, FITNESS, SLEEP)',
      skillId: 'skill-6-sleep-architecture',
      previewType: 'document',
      previewData: {
        docTitle: 'Digital Sunset Checklist',
        sections: [
          { title: 'Phase 1 (9:30 PM)', content: 'Turn off blue light monitors. Put smartphone in charging bay outside bedroom.' },
          { title: 'Phase 2 (10:00 PM)', content: 'Take Magnesium Glycinate (400mg). 10 minutes fiction reading under warm 2700K lighting.' },
          { title: 'Phase 3 (10:45 PM)', content: 'Blackout shades down. Thermostat set to 20°C.' },
        ],
      },
    },
  },

  // ==========================================
  // PILLAR 3: HOUSEHOLD WEALTH, TAXES & SMART SAVINGS
  // ==========================================
  {
    id: 'skill-7-wealth-tax',
    pillarId: 'pillar-3-wealth',
    pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
    name: 'Family Wealth, Budget & Tax Desk',
    icon: '💰',
    purpose: 'Tracks monthly household cashflow, Section 80C/80D tax deduction utilization, advance tax schedules, and expense ledgers.',
    triggers: {
      voiceCues: ['Paid ₹12,500 for term life insurance premium', 'Record advance tax payment', 'Grocery receipt logged'],
      multimodal: ['Photo of grocery bill, utility receipt, school fee receipt, tax challan'],
      scheduledCron: 'Quarterly Cron: Advance tax deadlines (June 15, Sept 15, Dec 15, March 15)',
    },
    targetArtifact: 'Google Sheets (Household_Cashflow_Master)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '💰 WEALTH & TAX DESK',
      sourceContext: 'Extracted from HDFC Life Insurance Premium Receipt PDF',
      headline: 'Term Life Premium Logged (₹12,500): Section 80C Deduction Updated',
      synthesis: '₹12,500 premium mapped to Section 80C deduction tracker. Cumulative 80C utilized: ₹1,12,500 / ₹1,50,000 max. Receipt backed up in Google Drive Tax Folder (/LifeOS/Taxes/FY2026-27/).',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Tax Deduction Ledger & Google Drive',
      targetArtifact: 'Google Sheets (Household_Cashflow_Master)',
      googleService: 'Google Sheets',
      pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
      skillId: 'skill-7-wealth-tax',
      previewType: 'invoice',
      previewData: {
        vendor: 'HDFC Life Click 2 Protect 3D Plus',
        invoiceNumber: 'POL-882190-26',
        amount: '₹12,500.00',
        dueDate: 'Paid (Annual Mode)',
        lineItems: [
          { desc: 'Pure Term Life Sum Assured ₹2.5 Crore', amount: '₹10,593.22' },
          { desc: '18% GST (Tax Eligible)', amount: '₹1,906.78' },
        ],
      },
    },
  },
  {
    id: 'skill-8-dormant-perks',
    pillarId: 'pillar-3-wealth',
    pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
    name: 'Dormant Benefits & Perks Optimizer',
    icon: '💳',
    purpose: 'Identifies unused benefits across credit cards (airport lounge visits, movie BOGO, fee waivers) and insurance perks.',
    triggers: {
      voiceCues: ['What credit card perks do I have?', 'Check lounge visits left'],
      scheduledCron: 'Quarterly Check: Evaluates expiry dates for card benefits and memberships',
    },
    targetArtifact: 'Google Tasks (Perk_Reminders)',
    googleService: 'Google Tasks',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '💳 PERKS OPTIMIZER',
      sourceContext: 'Quarterly Card Benefits Audit (Q4 Expiry Monitor)',
      headline: 'Claim 2 Complimentary Airport Lounge Visits & Annual Fee Spend Waiver',
      synthesis: 'Your primary Infinia card has 2 unused international lounge accesses expiring Dec 31. Current annual spend is ₹9.4 Lakhs—spending ₹60k before Oct 31 will trigger full annual fee waiver (saving ₹12,500).',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Credit Card Benefits Desk',
      targetArtifact: 'Google Tasks (Perk_Reminders)',
      googleService: 'Google Tasks',
      pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
      skillId: 'skill-8-dormant-perks',
      previewType: 'document',
      previewData: {
        docTitle: 'Card Benefits Audit',
        sections: [
          { title: 'Airport Lounge Balance', content: '2 International visits remaining on Priority Pass. Expires Dec 31, 2026.' },
          { title: 'Fee Waiver Milestone', content: 'Spent ₹9,40,000 / ₹10,00,000 threshold. Spend remaining: ₹60,000 to save ₹12,500 renewal fee.' },
          { title: 'BookMyShow BOGO', content: '2 free tickets up to ₹500 available this calendar month.' },
        ],
      },
    },
  },
  {
    id: 'skill-9-smart-shopping',
    pillarId: 'pillar-3-wealth',
    pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
    name: 'Smart Shopping & Price Optimizer',
    icon: '🏷️',
    purpose: 'Price tracking, card discount optimization, festive deals, and medicine cost comparison.',
    triggers: {
      voiceCues: ['Find best deal for whey protein powder 2kg', 'Compare price of Januvia 100mg', 'Track price for Sony headphones'],
    },
    targetArtifact: 'Google Keep Note (Saved_Deals_Watchlist)',
    googleService: 'Google Keep',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '🏷️ PRICE OPTIMIZER',
      sourceContext: 'Voice directive: "Find best deal for whey protein powder 2kg"',
      headline: 'Arbitrage Deal Found: Optimum Nutrition Whey 2kg at 28% Discount + Card Offer',
      synthesis: 'Base MRP: ₹7,899. Found on Platform A at ₹5,699. An additional 10% instant discount (₹570) applies with your connected HDFC card, bringing net price to ₹5,129 (Lowest in 90 days).',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Verified Nutrition E-Commerce',
      targetArtifact: 'Google Keep Note (Saved_Deals_Watchlist)',
      googleService: 'Google Keep',
      pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
      skillId: 'skill-9-smart-shopping',
      previewType: 'invoice',
      previewData: {
        vendor: 'Optimum Nutrition Gold Standard (2kg Double Rich Chocolate)',
        invoiceNumber: 'DEAL-ARBITRAGE-99',
        amount: '₹5,129.00 (Net)',
        dueDate: 'Deal expires in 14 hours',
        lineItems: [
          { desc: 'Retail Listed Price', amount: '₹7,899.00' },
          { desc: 'Flash Sale Discount (-28%)', amount: '-₹2,200.00' },
          { desc: 'Instant Card Discount (-10%)', amount: '-₹570.00' },
        ],
      },
    },
  },
  {
    id: 'skill-10-investment-allocator',
    pillarId: 'pillar-3-wealth',
    pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
    name: 'Long-Term Investment Allocator',
    icon: '📈',
    purpose: 'Models index fund allocations, debt-equity portfolio balance, and annual rebalancing rules.',
    triggers: {
      voiceCues: ['Review monthly SIP allocation', 'Rebalance portfolio', 'Deploy ₹50,000 bonus'],
      scheduledCron: 'Monthly Cron (1st of month): SIP reminder and cashflow allocation audit',
    },
    targetArtifact: 'Google Sheets (Portfolio_Asset_Allocation)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '📈 INVESTMENT ALLOCATOR',
      sourceContext: 'Monthly Automated Portfolio Audit (1st of Month)',
      headline: 'Execute Monthly SIP & Portfolio Rebalance: ₹50,000 Allocation Prepared',
      synthesis: 'Current Equity:Debt ratio is 72:28 (Target policy: 70:30). Directing ₹30,000 to Nifty 50 Index Fund, ₹10,000 to Parag Parikh Flexi Cap, and ₹10,000 to Target Maturity Debt Fund to restore optimal asset mix.',
      urgency: 'high',
      isKeystone: false,
      targetEntity: 'Registered Mutual Fund Registrar (Zerodha / Groww)',
      targetArtifact: 'Google Sheets (Portfolio_Asset_Allocation)',
      googleService: 'Google Sheets',
      pillarName: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
      skillId: 'skill-10-investment-allocator',
      previewType: 'document',
      previewData: {
        docTitle: 'Asset Rebalance & SIP Deployment Plan',
        sections: [
          { title: 'Nifty 50 Index Fund', content: '₹30,000 (Low-cost broad market beta allocation).' },
          { title: 'Global / Flexi Cap Fund', content: '₹10,000 (International tech exposure & alpha diversification).' },
          { title: 'Government Debt / Arbitrage', content: '₹10,000 (Preserves capital for emergency buffer).' },
        ],
      },
    },
  },

  // ==========================================
  // PILLAR 4: HOME OPS, DOMESTIC STAFF & MOBILITY
  // ==========================================
  {
    id: 'skill-11-domestic-staff',
    pillarId: 'pillar-4-home-ops',
    pillarName: 'HOME OPS, DOMESTIC STAFF & MOBILITY',
    name: 'Domestic Staff & Home Ops Manager',
    icon: '🧹',
    purpose: 'Tracks maid, cook, and driver attendance, salary ledgers, advance payments, and society maintenance dues.',
    triggers: {
      voiceCues: ['Ramesh cook took ₹2,000 cash advance today', 'Kamla maid on leave today', 'Pay society maintenance'],
      scheduledCron: 'Monthly Cron (Last day of month): Pre-calculates final payable wages',
    },
    targetArtifact: 'Google Sheets (Domestic_Staff_Ledger)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '🧹 STAFF OPS LEDGER',
      sourceContext: 'Monthly Payroll Audit: Ramesh (Cook) & Kamla (Maid)',
      headline: 'Approve End-of-Month Staff Salary Settlement: Ramesh (₹6,000) & Kamla (₹4,500)',
      synthesis: 'Calculations: Ramesh (Cook): Base ₹8,000 - ₹2,000 Cash Advance (Logged Oct 14) = Net Payable ₹6,000. Kamla (Maid): Base ₹4,500 - 0 leaves = Net Payable ₹4,500. Ready for 1-tap UPI disbursement.',
      urgency: 'high',
      isKeystone: true,
      targetEntity: 'Domestic Staff Ledger & UPI Dispatch',
      targetArtifact: 'Google Sheets (Domestic_Staff_Ledger)',
      googleService: 'Google Sheets',
      pillarName: 'HOME OPS, DOMESTIC STAFF & MOBILITY',
      skillId: 'skill-11-domestic-staff',
      previewType: 'invoice',
      previewData: {
        vendor: 'Domestic Staff Payroll (October 2026)',
        invoiceNumber: 'STAFF-PAY-2026-10',
        amount: '₹10,500.00 Total',
        dueDate: 'Last day of month',
        lineItems: [
          { desc: 'Ramesh (Cook) Net Salary [₹8k base - ₹2k advance]', amount: '₹6,000.00' },
          { desc: 'Kamla (Maid) Net Salary [Full Attendance]', amount: '₹4,500.00' },
        ],
      },
    },
  },
  {
    id: 'skill-12-vehicle-mobility',
    pillarId: 'pillar-4-home-ops',
    pillarName: 'HOME OPS, DOMESTIC STAFF & MOBILITY',
    name: 'Vehicle Care & Mobility Desk',
    icon: '🚗',
    purpose: 'Tracks car service schedules, motor insurance renewals, FASTag balance, PUC certifications, and service histories.',
    triggers: {
      voiceCues: ['Car serviced at 32,000 km, oil changed, cost ₹6,400', 'FASTag balance low', 'Check PUC expiry'],
      scheduledCron: 'Scheduled Check: 30 days and 10 days before PUC or motor insurance expiry',
    },
    targetArtifact: 'Google Calendar (Renewal events) + Google Sheets (Vehicle_Service_History)',
    googleService: 'Google Calendar',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '🚗 MOBILITY DESK',
      sourceContext: 'Automated Compliance Monitor: PUC Certificate Expiry Alert',
      headline: 'Renew PUC Emission Certificate for Honda City (DL-10-XX-0000) Expiring in 8 Days',
      synthesis: 'Statutory PUC certificate expires on Oct 9. Failure to renew invites ₹10,000 penalty under MV Act §190(2). Nearest certified testing center is Indian Oil Station (800m away). Pre-blocked Saturday 10:00 AM on Google Calendar.',
      urgency: 'high',
      isKeystone: true,
      targetEntity: 'RTO Compliance / Vehicle Ledger',
      targetArtifact: 'Google Calendar (Renewal events)',
      googleService: 'Google Calendar',
      pillarName: 'HOME OPS, DOMESTIC STAFF & MOBILITY',
      skillId: 'skill-12-vehicle-mobility',
      previewType: 'document',
      previewData: {
        docTitle: 'Vehicle Compliance Spec',
        sections: [
          { title: 'Vehicle Identification', content: 'Honda City ZX (DL-10-XX-0000). Chasis Ending: 9482.' },
          { title: 'Expiration Date', content: 'October 9, 2026 (8 days remaining).' },
          { title: 'Recommended Action', content: '10-minute drive-through test at IOCL Petrol Pump, Main Avenue. Saturday 10 AM hold added to calendar.' },
        ],
      },
    },
  },
  {
    id: 'skill-13-renovation-estimator',
    pillarId: 'pillar-4-home-ops',
    pillarName: 'HOME OPS, DOMESTIC STAFF & MOBILITY',
    name: 'Contractor & Home Renovation Estimator',
    icon: '🔨',
    purpose: 'Audits renovation quotes, carpentry estimates, material specifications, and contractor milestone payments.',
    triggers: {
      voiceCues: ['Audit carpenter quote', 'Review plumbing estimate'],
      multimodal: ['Photo or PDF of carpenter/plumber handwritten quote or interior estimate'],
    },
    targetArtifact: 'Google Docs (Renovation_Estimate_Audit)',
    googleService: 'Google Docs',
    actionCardTemplate: {
      category: 'artifacts',
      categoryLabel: '🔨 CONTRACTOR AUDIT',
      sourceContext: 'Parsed from scanned handwritten contractor quotation photo',
      headline: 'Audit Contractor Quote: Electrical Wiring Quoted 20% Above Regional Market Rate',
      synthesis: 'Quotation total: ₹45,000 for Master Bedroom electrical overhaul. LifeOS audited line items: 2.5mm Finolex copper wire quoted at ₹2,800/coil (Retail benchmark is ₹2,250/coil). Counter-offer drafted requesting 15% rate alignment.',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Contractor Sharma Electricals',
      targetArtifact: 'Google Docs (Renovation_Estimate_Audit)',
      googleService: 'Google Docs',
      pillarName: 'HOME OPS, DOMESTIC STAFF & MOBILITY',
      skillId: 'skill-13-renovation-estimator',
      previewType: 'document',
      previewData: {
        docTitle: 'Independent Contractor Audit Report',
        sections: [
          { title: 'Total Claimed', content: '₹45,000 (Labor: ₹18,000 | Materials: ₹27,000).' },
          { title: 'Flagged Discrepancy', content: 'Copper wiring marked up 24% over standard retail. Labor days calculated at 6 days vs estimated 4 days.' },
          { title: 'Negotiation Target', content: 'Counter-offer drafted at ₹38,500 with milestone payment: 40% upfront, 60% on completion & circuit breaker testing.' },
        ],
      },
    },
  },

  // ==========================================
  // PILLAR 5: SOVEREIGN IDENTITY, DOCUMENTS & LEGAL ESTATE
  // ==========================================
  {
    id: 'skill-14-kyc-id-vault',
    pillarId: 'pillar-5-identity',
    pillarName: 'SOVEREIGN IDENTITY, DOCUMENTS & LEGAL ESTATE',
    name: 'Sovereign KYC & ID Vault',
    icon: '🪪',
    purpose: 'Securely catalogs and indexes identification documents (Aadhaar, Passport, PAN, Voter ID), property papers, and vehicle registration.',
    triggers: {
      voiceCues: ['What is my passport expiry date?', 'Find my PAN number', 'Catalog this Aadhaar card'],
      multimodal: ['Photo of Aadhaar, Passport, PAN card, or Vehicle Registration Certificate'],
    },
    targetArtifact: 'Google Drive (/LifeOS/Identity_Vault/) with strict encryption',
    googleService: 'Google Drive',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '🪪 IDENTITY VAULT',
      sourceContext: 'Multimodal OCR from uploaded Indian Passport photo',
      headline: 'Passport Cataloged to Secure Vault: Expiry August 2031 (Valid 5 Years)',
      synthesis: 'Passport ending in 8492 successfully OCR-parsed and encrypted. Extracted: Name: Principal Executive, DOB: 14/08/1988, Place of Issue: New Delhi. Saved to encrypted folder in Google Drive. 6-month pre-expiry reminder scheduled.',
      urgency: 'medium',
      isKeystone: true,
      targetEntity: 'Encrypted Sovereign Identity Vault',
      targetArtifact: 'Google Drive (/LifeOS/Identity_Vault/)',
      googleService: 'Google Drive',
      pillarName: 'SOVEREIGN IDENTITY, DOCUMENTS & LEGAL ESTATE',
      skillId: 'skill-14-kyc-id-vault',
      previewType: 'document',
      previewData: {
        docTitle: 'Encrypted Identity Index: Passport',
        sections: [
          { title: 'Document Number', content: 'Z-••••-8492 (Valid through Aug 2031)' },
          { title: 'Biographical Accuracy', content: 'Name and DOB match connected PAN and Aadhaar records perfectly.' },
          { title: 'Storage Encryption', content: 'Stored in Google Drive /LifeOS/Identity_Vault/ with zero-knowledge metadata indexing.' },
        ],
      },
    },
  },
  {
    id: 'skill-15-legal-estate',
    pillarId: 'pillar-5-identity',
    pillarName: 'SOVEREIGN IDENTITY, DOCUMENTS & LEGAL ESTATE',
    name: 'Family Legal Estate & Will Planner',
    icon: '⚖️',
    purpose: 'Organizes family asset registries, account nominee verifications, succession records, and basic will drafting frameworks.',
    triggers: {
      voiceCues: ['Check bank nominee status', 'Audit family estate records', 'Who is nominee on my demat?'],
      scheduledCron: 'Annual Estate Health Check protocol card',
    },
    targetArtifact: 'Google Sheets (Asset_and_Nominee_Registry)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '⚖️ LEGAL ESTATE',
      sourceContext: 'Annual Sovereign Estate & Nominee Verification Audit',
      headline: 'Bank Account Nominee Health-Check: 2 Investment Accounts Lack Recorded Nominee',
      synthesis: 'Audit of 6 financial holdings reveals that 2 demat accounts (Zerodha & ICICI Direct) lack updated secondary nominee registration. Failure to record nominees creates probate friction for heirs. Action checklist prepared.',
      urgency: 'high',
      isKeystone: true,
      targetEntity: 'Family Estate Registry (Google Sheets)',
      targetArtifact: 'Google Sheets (Asset_and_Nominee_Registry)',
      googleService: 'Google Sheets',
      pillarName: 'SOVEREIGN IDENTITY, DOCUMENTS & LEGAL ESTATE',
      skillId: 'skill-15-legal-estate',
      previewType: 'document',
      previewData: {
        docTitle: 'Estate Nominee Verification Findings',
        sections: [
          { title: 'Compliant Accounts', content: '✓ HDFC Salary Account (Nominee: Spouse - 100%)\n✓ PPF Account (Nominee: Spouse - 100%)\n✓ Term Life Policy (Nominee: Spouse - 100%)' },
          { title: 'Non-Compliant Holdings', content: '⚠️ Zerodha Demat #19482 (No secondary nominee listed)\n⚠️ ICICI Direct Mutual Fund Folio (Nominee unverified)' },
          { title: 'Recommended Next Step', content: 'Update online via Digilocker e-sign in 5 minutes using provided links.' },
        ],
      },
    },
  },

  // ==========================================
  // PILLAR 6: FOCUS, ENERGY & DAILY CADENCE
  // ==========================================
  {
    id: 'skill-16-daily-north-star',
    pillarId: 'pillar-6-cadence',
    pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
    name: 'Single Daily North Star Filter',
    icon: '🎯',
    purpose: 'Filters out backlog noise and surfaces strictly 1 to 3 needle-moving priorities per day in Today’s Runway.',
    triggers: {
      voiceCues: ['What is my #1 priority today?', 'Filter daily backlog', 'Set today north stars'],
      scheduledCron: 'Morning Cron (6:00 AM): Evaluates active missions and selects top leverage actions',
    },
    targetArtifact: 'Google Tasks (Starred daily tasks)',
    googleService: 'Google Tasks',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '🎯 NORTH STAR FILTER',
      sourceContext: 'Morning Cron (6:00 AM) Algorithm Evaluation',
      headline: 'Commit Today’s 2 High-Leverage North Stars to Daily Runway',
      synthesis: 'Backlog filtered from 24 items down to 2 essential needle-movers: 1. Finalize driving license test booking; 2. Settle quarterly advance tax. All secondary administrative noise quarantined.',
      urgency: 'high',
      isKeystone: true,
      targetEntity: 'Today’s Runway Execution Queue',
      targetArtifact: 'Google Tasks (Starred daily tasks)',
      googleService: 'Google Tasks',
      pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
      skillId: 'skill-16-daily-north-star',
      previewType: 'document',
      previewData: {
        docTitle: 'Today’s Sovereign North Stars',
        sections: [
          { title: 'North Star #1 (S-Tier)', content: 'Finalize driving license test booking at RTO South (Unlocks personal mobility independence).' },
          { title: 'North Star #2 (A-Tier)', content: 'Settle Q3 advance tax installment before 5 PM statutory deadline to avoid interest penalties.' },
        ],
      },
    },
  },
  {
    id: 'skill-17-friction-breaker',
    pillarId: 'pillar-6-cadence',
    pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
    name: 'Micro-Timer Friction Breaker',
    icon: '⏱️',
    purpose: 'Guides 5- to 15-minute countdown sprints and micro-commitments to overcome heavy task inertia and procrastination.',
    triggers: {
      voiceCues: ['I am dreading cleaning my desk', 'Start a 10-minute focus sprint', 'Friction breaker on quarterly report'],
      scheduledCron: 'One-Tap Chip in Runway: [ ⏱️ 10m Micro-Sprint ]',
    },
    targetArtifact: 'In-App Audio/Visual Countdown Timer + Google Tasks',
    googleService: 'Google Tasks',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '⏱️ FRICTION BREAKER',
      sourceContext: 'Activated via Micro-Timer Friction Breaker Protocol',
      headline: 'Launch 10-Minute Micro-Commitment Sprint (Free to Stop at Bell)',
      synthesis: 'Psychological protocol active: Commit only to opening the desk clutter and sorting papers for 10 minutes. If motivation remains low when timer sounds, you have full sovereign permission to stop.',
      urgency: 'high',
      isKeystone: false,
      targetEntity: 'In-App Interactive Sprint Player',
      targetArtifact: 'In-App Audio/Visual Countdown Timer',
      googleService: 'Google Tasks',
      pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
      skillId: 'skill-17-friction-breaker',
      previewType: 'document',
      previewData: {
        docTitle: '10-Minute Sprint Contract',
        sections: [
          { title: 'The 10-Minute Rule', content: 'Task inertia vanishes after 180 seconds of physical action. No perfection required.' },
          { title: 'Micro Objective', content: 'Clear physical desktop surface and discard empty bottles/scrap notes.' },
        ],
      },
    },
  },
  {
    id: 'skill-18-nightly-winddown',
    pillarId: 'pillar-6-cadence',
    pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
    name: 'Nightly Wind-Down & Extraction Session',
    icon: '🌙',
    purpose: '2-minute evening review to clear mental open loops, log gratitude, and prep tomorrow’s focus.',
    triggers: {
      voiceCues: ['Ready for nightly wind down', 'Log daily win', 'Clear open loops before bed'],
      scheduledCron: 'Evening Cron (9:00 PM): Prompts evening wind-down in Cockpit',
    },
    targetArtifact: 'Google Keep (Daily_Reflections) + Google Tasks (Tomorrow queue)',
    googleService: 'Google Keep',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '🌙 NIGHTLY WIND-DOWN',
      sourceContext: 'Evening Cadence Cron (9:00 PM)',
      headline: 'Initiate 2-Minute Nightly Wind-Down & Open Loop Extraction',
      synthesis: 'Unload working memory before sleep. Speak a 30-second memo answering: What was your #1 win today? What lingering open loop needs to be scheduled for tomorrow morning so you can rest completely?',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Google Keep (Daily_Reflections)',
      targetArtifact: 'Google Keep (Daily_Reflections)',
      googleService: 'Google Keep',
      pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
      skillId: 'skill-18-nightly-winddown',
      previewType: 'document',
      previewData: {
        docTitle: 'Nightly Reflection Prompts',
        sections: [
          { title: 'Win of the Day', content: 'What moved the needle forward today?' },
          { title: 'Open Loop Buffer', content: 'Any lingering emails or to-dos? Voice memo them now and Chief of Staff will queue them tomorrow at 9 AM.' },
        ],
      },
    },
  },
  {
    id: 'skill-19-cyber-hygiene',
    pillarId: 'pillar-6-cadence',
    pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
    name: 'Digital Declutter & Cyber Hygiene Guard',
    icon: '🔒',
    purpose: 'Maintains password rotation reminders, 2FA backup verification, and cloud storage cleanup routines.',
    triggers: {
      voiceCues: ['Check cyber hygiene', 'Verify 2FA backup codes', 'Clean up Google Drive storage'],
      scheduledCron: 'Quarterly Protocol: Alerts on storage thresholds or 2FA backup reviews',
    },
    targetArtifact: 'Google Tasks (Cyber_Hygiene_Checklist)',
    googleService: 'Google Tasks',
    actionCardTemplate: {
      category: 'protocols',
      categoryLabel: '🔒 CYBER HYGIENE',
      sourceContext: 'Quarterly Security Audit Protocol',
      headline: 'Execute Cyber Hygiene Audit: Verify 2FA Backup Codes & Primary Cloud Storage',
      synthesis: 'Security review recommends rotating master passwords and downloading offline physical recovery codes for primary Google Account, Password Manager, and Banking Portal.',
      urgency: 'medium',
      isKeystone: false,
      targetEntity: 'Cyber Security Checklist',
      targetArtifact: 'Google Tasks',
      googleService: 'Google Tasks',
      pillarName: 'FOCUS, ENERGY & DAILY CADENCE',
      skillId: 'skill-19-cyber-hygiene',
      previewType: 'document',
      previewData: {
        docTitle: 'Cyber Security Checklist',
        sections: [
          { title: '1. Google 2FA Backup', content: 'Verify 8-digit printable one-time backup codes are stored in offline fireproof lockbox.' },
          { title: '2. Cloud Storage Audit', content: 'Google Drive at 82% capacity. Review large video files in Trash to prevent auto-sync stall.' },
          { title: '3. Device Session Review', content: 'Check active authorized sessions in Google Security Console.' },
        ],
      },
    },
  },

  // ==========================================
  // PILLAR 7: FAMILY RELATIONSHIPS & SOCIAL MILESTONES
  // ==========================================
  {
    id: 'skill-20-social-calendar',
    pillarId: 'pillar-7-relationships',
    pillarName: 'FAMILY RELATIONSHIPS & SOCIAL MILESTONES',
    name: 'Family Relationships & Social Calendar',
    icon: '🎂',
    purpose: 'Tracks family birthdays, wedding anniversaries, social milestones, and gift ideas.',
    triggers: {
      voiceCues: ['Mother birthday coming up', 'Add wedding anniversary on Oct 24', 'Gift idea for brother'],
      scheduledCron: 'Scheduled Check: 7 days and 1 day before an anniversary or birthday',
    },
    targetArtifact: 'Google Calendar (Annual recurring events with notifications)',
    googleService: 'Google Calendar',
    actionCardTemplate: {
      category: 'responses',
      categoryLabel: '🎂 SOCIAL MILESTONE',
      sourceContext: 'Automated Family Milestone Monitor: 6 Days Remaining',
      headline: 'Mother’s 62nd Birthday in 6 Days (Oct 7): Dinner Reservation & Gift Plan',
      synthesis: 'Past preference notes indicate Mother appreciates handwoven silk stoles or dinner at ITC Gardenia. Suggested plan: Pre-reserve table for 4 at 7:30 PM and order Kashmiri Kani shawl from curated boutique.',
      urgency: 'high',
      isKeystone: false,
      targetEntity: 'Family Milestone Calendar',
      targetArtifact: 'Google Calendar (Annual recurring events)',
      googleService: 'Google Calendar',
      pillarName: 'FAMILY RELATIONSHIPS & SOCIAL MILESTONES',
      skillId: 'skill-20-social-calendar',
      previewType: 'document',
      previewData: {
        docTitle: 'Milestone Celebration Plan',
        sections: [
          { title: 'Event Details', content: 'Mother’s Birthday: October 7, 2026 (Annual recurring event).' },
          { title: 'Gift Notes', content: 'Past Favorites: Handwoven silk stoles, Ayurvedic wellness sets, hardbound historical fiction.' },
          { title: 'Calendar Hold', content: 'Block family dinner Wednesday Oct 7 at 7:30 PM.' },
        ],
      },
    },
  },
  {
    id: 'skill-21-festive-sales',
    pillarId: 'pillar-7-relationships',
    pillarName: 'FAMILY RELATIONSHIPS & SOCIAL MILESTONES',
    name: 'Gifts & Festive Sales Arbitrageur',
    icon: '🪔',
    purpose: 'Pre-plans Diwali, festive, and wedding gifts during mega-sales using price tracking and card offers.',
    triggers: {
      voiceCues: ['Plan Diwali gifts', 'Review festive shopping budget', 'Buy dry fruit gift boxes'],
      scheduledCron: 'Seasonal Cron (4 weeks before major festivals): Surfaces festive gifting review',
    },
    targetArtifact: 'Google Sheets (Festive_Gifting_Ledger)',
    googleService: 'Google Sheets',
    actionCardTemplate: {
      category: 'lifeops',
      categoryLabel: '🪔 FESTIVE ARBITRAGE',
      sourceContext: 'Seasonal Festival Pre-Planning Cron (4 Weeks Before Diwali)',
      headline: 'Activate Festive Gifting Runway: 8 Family Gifts Mapped to Mega Sale Window',
      synthesis: 'Great Indian Festival & Big Billion Days active this week. Pre-mapped 8 family gifts (Dry fruit hampers, silver coins, electronics) to leverage 10% instant card discounts, saving estimated ₹14,200 on festive budget.',
      urgency: 'high',
      isKeystone: false,
      targetEntity: 'Festive Gifting Ledger',
      targetArtifact: 'Google Sheets (Festive_Gifting_Ledger)',
      googleService: 'Google Sheets',
      pillarName: 'FAMILY RELATIONSHIPS & SOCIAL MILESTONES',
      skillId: 'skill-21-festive-sales',
      previewType: 'invoice',
      previewData: {
        vendor: 'Festive Gifting Master Plan (Diwali 2026)',
        invoiceNumber: 'FESTIVE-GIFT-2026',
        amount: '₹38,500.00 Budget (Estimated Savings: ₹14,200)',
        dueDate: 'Optimal Order Window: Oct 3 - Oct 8',
        lineItems: [
          { desc: 'Artisanal Organic Dry Fruit Gift Boxes (x6)', amount: '₹14,400.00' },
          { desc: '999 Pure Silver Laxmi-Ganesh Coins (x2)', amount: '₹8,600.00' },
          { desc: 'Smart Tablet for Parents (With HDFC instant 10% off)', amount: '₹15,500.00' },
        ],
      },
    },
  },
];

// Helper to group skills by Pillar
export const PILLAR_GROUPS: LifePillarGroup[] = [
  {
    id: 'pillar-1-health',
    number: 1,
    name: 'HEALTH, EMERGENCY & CLINICAL VAULT',
    tagline: 'Rapid medical response, diagnostic trending, and proactive health cadences.',
    icon: '🛡️',
    skills: LIFE_SKILLS_CATALOG.filter((s) => s.pillarId === 'pillar-1-health'),
  },
  {
    id: 'pillar-2-vitality',
    number: 2,
    name: 'DAILY VITALITY & BODY',
    tagline: 'Household meal planning, progressive fitness programming, and circadian sleep shields.',
    icon: '🥗',
    skills: LIFE_SKILLS_CATALOG.filter((s) => s.pillarId === 'pillar-2-vitality'),
  },
  {
    id: 'pillar-3-wealth',
    number: 3,
    name: 'HOUSEHOLD WEALTH, TAXES & SMART SAVINGS',
    tagline: 'Tax deductions (80C/80D), credit card perk arbitrage, and asset allocation.',
    icon: '💰',
    skills: LIFE_SKILLS_CATALOG.filter((s) => s.pillarId === 'pillar-3-wealth'),
  },
  {
    id: 'pillar-4-home-ops',
    number: 4,
    name: 'HOME OPS, DOMESTIC STAFF & MOBILITY',
    tagline: 'Staff salary settlements, vehicle compliance (PUC/FASTag), and contractor auditing.',
    icon: '🧹',
    skills: LIFE_SKILLS_CATALOG.filter((s) => s.pillarId === 'pillar-4-home-ops'),
  },
  {
    id: 'pillar-5-identity',
    number: 5,
    name: 'SOVEREIGN IDENTITY, DOCUMENTS & LEGAL ESTATE',
    tagline: 'Encrypted document vaults (Passport, Aadhaar) and succession nominee checks.',
    icon: '🪪',
    skills: LIFE_SKILLS_CATALOG.filter((s) => s.pillarId === 'pillar-5-identity'),
  },
  {
    id: 'pillar-6-cadence',
    number: 6,
    name: 'FOCUS, ENERGY & DAILY CADENCE',
    tagline: 'Single daily north stars, 10-minute micro-sprints, and nightly wind-down extraction.',
    icon: '🎯',
    skills: LIFE_SKILLS_CATALOG.filter((s) => s.pillarId === 'pillar-6-cadence'),
  },
  {
    id: 'pillar-7-relationships',
    number: 7,
    name: 'FAMILY RELATIONSHIPS & SOCIAL MILESTONES',
    tagline: 'Birthday/anniversary alerts and festive gifting price arbitrage.',
    icon: '🎂',
    skills: LIFE_SKILLS_CATALOG.filter((s) => s.pillarId === 'pillar-7-relationships'),
  },
];

/**
 * Spawns an actionable ActionCard from any LifeSkill
 */
export function spawnActionCardFromSkill(skillId: string): ActionCard | null {
  const skill = LIFE_SKILLS_CATALOG.find((s) => s.id === skillId);
  if (!skill) return null;

  const template = skill.actionCardTemplate;
  const now = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  return {
    ...template,
    id: `card-skill-${skill.id}-${Date.now()}`,
    status: 'pending',
    createdAt: new Date().toISOString(),
    sourceContext: `Triggered from ${skill.name} Protocol (${now})`,
    targetArtifact: skill.targetArtifact,
    googleService: skill.googleService,
    pillarName: skill.pillarName,
    skillId: skill.id,
  };
}
